- name: SettingUp nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: SettingUp nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: mongo_schema_setup
