- name: SettingUp Python
  ansible.builtin.import_role:
    name: common
    tasks_from: python

- name: Load prometheus node exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter