- name: Adding the Application user
  ansible.builtin.user:
    name: roboshop

- name: Remove the Directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading the {{ component }} content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes
