- name: Download server repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install Nodejs Server
  ansible.builtin.yum:
    name: nodejs
    state: latest

- name: Import app_presetup
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: Installing NodeJs Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Import systemd_setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
