- name: Copying the {{ component }}.service file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Enabling and restarting {{ component }} Server
  ansible.builtin.systemd:
    state: restarted
    name: "{{ component }}"
    enabled: true
    daemon_reload: true