- name: SettingUp nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Load prometheus node exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter